### ISSUE TITLE
Make `GetLog()` available in the Python binding

### ISSUE THREAD

**Issue by apacha** [rism-ch/verovio#2057]
I've switched to the Python SDK for Verovio, and I want to capture the information that is being given when trying to load a file. However, the output get's always written directly to the output and I can't seem to capture it. So my question is, how can I capture that essential output that Verovio produces?

More precisely, my code looks like this:

```python
import verovio
verovio_toolkit = verovio.toolkit()
verovio_toolkit.loadFile(path_to_musicxml_file)
```
when I inspect the output console, it prints information like:
```text
[Warning] Insufficient space to draw mixed beam, starting at 'note-132'. Drawing 'above' instead.
[Warning] Insufficient space to draw mixed beam, starting at 'note-132'. Drawing 'above' instead.
[Warning] Insufficient space to draw mixed beam, starting at 'note-132'. Drawing 'above' instead.
[Warning] Insufficient space to draw mixed beam, starting at 'note-132'. Drawing 'above' instead.
```
that I want to capture in a string.

The obvious `verovio_toolkit.getLog()` always returns an empty string. I wish it would contain the same information, but currently it doesn't - do I need to configure it somehow first?

My next assumption was, that the toolkit is writing information to std_out or std_err, because it only returns a boolean value. With that in mind, I tried the following:

```python
import io
from contextlib import redirect_stdout
with io.StringIO() as buf, redirect_stdout(buf):
    verovio_toolkit.loadFile(path_to_musicxml_file)
    output = buf.getvalue()
```
and
```python
import io
from contextlib import redirect_stderr
with io.StringIO() as buf, redirect_stderr(buf):
    verovio_toolkit.loadFile(path_to_musicxml_file)
    output = buf.getvalue()
```
but in both cases, the output was still written to the console and `output` remained an empty string.

Can anyone tell me, what I'm doing wrong here?

**Comment by ahankinson** [comment]
Did you try redirecting stdlog?

**Comment by rettinghaus** [comment]
`GetLog()` strangely is only available in the JS toolkit. Shouldn't we have that for the Python package too, @lpugin?

**Comment by apacha** [comment]
@ahankinson What is stdlog and how can I redirect it?

**Comment by apacha** [comment]
For reference, this is where the logging happens, which would indicate that the messages are being written to std_err: https://github.com/rism-ch/verovio/blob/66a23911172ae59f0eb765a6f3a5c3e6142a877e/src/vrv.cpp#L390-L408

That would mean, it should (in theory) be possible to capture std_err and read those message. But I agree with @rettinghaus, writing to the log-file as in case of the JS toolkit would be the best option.

**Comment by ahankinson** [comment]
To be more precise, it happens here: https://github.com/rism-ch/verovio/blob/66a23911172ae59f0eb765a6f3a5c3e6142a877e/src/vrv.cpp#L426-L438

Which, I think, means that verovio is delegating writing the log messages to the Emscripten library. Where it goes from there (through the various `console` calls) might be able to give you a clue to how to capture it?

**Comment by ahankinson** [comment]
Nevermind my earlier comment; I was wrong.

**Comment by rettinghaus** [comment]
Should we rely on `logging`? Then we could do something with `Python.h` as shown [here](https://gist.github.com/hensing/0db3f8e3a99590006368).

**Comment by ahankinson** [comment]
You can redirect stderr to the logging code in your own Python application if you want: 

https://stackoverflow.com/a/66209331

This would then handle logging to file. The logging module in Python is quite comprehensive, but also a bit on the "huh, wut?" side, particularly when it comes to configuring formatters, streams, loggers, etc.

**Comment by ahankinson** [comment]
For example, here's a logging configuration that I use quite often:

```
version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: "[%(asctime)s] [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  consoledebug:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ./indexer.log
    when: D
    backupCount: 7
loggers:
  muscat_indexer:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: NOTSET
```

Changing the different parameters means that you can configure production applications to write to automatically timed rotating files, which is quite cool, and also configure different logging levels to different outputs simultaneously (write errors to the file, write info to the console, etc.)
