### ISSUE TITLE
lyrics and chords font

### ISSUE THREAD

**Issue by sannedubois** [rism-ch/verovio#336]
It would be nice to be able to give lyrics and chords a different font, using css. Giving both a different color is possible using css.

**Comment by rettinghaus** [comment]
But it is already! Try this:
```css
svg g.harm text tspan {font-family:Helvetica;}
svg g.syl text tspan {font-family:Arial;}
```

**Comment by lpugin** [comment]
Alternatively you can use `<rend>` in the MEI

**Comment by rettinghaus** [comment]
... or `ATT_LYRICSTYLE` on `<staffDef>`

**Comment by sannedubois** [comment]
HEllo KLaus,

Thanks. Great!

I have a wish for which I'm wondering wheather it could be easily solved
with the use of css. When zooming in/out it would be nice to keep the upper
left point of the first staff at the same place. Do you know if there's a
simple css soluton for that?

Kind regards,
Derk

2016-10-21 12:41 GMT+02:00 Klaus Rettinghaus <notifications@github.com>:

**Comment by sannedubois** [comment]
Thanks Klaus,

You are right. Works perfectly.

Kind regards,
Derk

2016-10-20 18:54 GMT+02:00 Klaus Rettinghaus <notifications@github.com>:

**Comment by rettinghaus** [comment]
How do you zoom? Assuming you do it with Javascript: you should apply negative css margins to top and left and change them while zooming in and out accordingly, e.g.

```css
svg:not(:root) {
    margin-top: -2%;
    margin-left: -1em;
}
```
