### ISSUE TITLE
notehead/stem interaction in SVG renderings

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#520]
Stems (similar to ledger lines) should be written to the SVG before noteheads, otherwise the stems occlude the notehead:

<img width="332" alt="screen shot 2017-03-13 at 10 53 37 am" src="https://cloud.githubusercontent.com/assets/3487289/23868119/817bf7c6-07db-11e7-8ce1-3dc58f240922.png">

```xml
<g class="note highlight" id="note-L13F1" fill="red" stroke="red">
   <use xlink:href="#E0A4" x="6421" y="1535" height="720px" width="720px" />
   <rect x="6421" y="1557" height="608" width="20" />
</g>
```

If the order were changed:

<img width="300" alt="screen shot 2017-03-13 at 10 56 31 am" src="https://cloud.githubusercontent.com/assets/3487289/23868181/bffe79f6-07db-11e7-852e-a26f8fbc25d7.png">

```xml
<g class="note highlight" id="note-L13F1" fill="red" stroke="red">
   <rect x="6421" y="1557" height="608" width="20" />
   <use xlink:href="#E0A4" x="6421" y="1535" height="720px" width="720px" />
</g>
```

It might also be nice to label sub-components of the note element with class tags for more semantic addressing with CSS:

```xml
<g class="note highlight" id="note-L13F1" fill="red" stroke="red">
   <rect class="stem" x="6421" y="1557" height="608" width="20" />
   <use class="head" xlink:href="#E0A4" x="6421" y="1535" height="720px" width="720px" />
</g>
```

CSS currently:
```css
<style>

svg .note.highlight use {
        fill: violet;
}

svg .note.highlight rect {
        fill: red;
}

</style>
```

would become:

```css
<style>
svg .note.highlight .head {
        fill: violet;
}

svg .note.highlight .stem {
        fill: red;
}

</style>
```
